### PR TITLE
Ignore dropped columns when pulling schema metadata

### LINKED ISSUE #18: Data API local fails if a table has a dropped column
The query to pull schema information from Postgres fails if a table has a dropped column:

```
2020-12-03 11:06:06.539 EST [20366] ERROR:  column "........pg.dropped.2........" of relation "xyz" does not exist
2020-12-03 11:06:06.539 EST [20366] STATEMENT:
                SELECT
                  c.oid AS "tableID",
                  a.attnum AS "columnID",
                  c.relname AS "tableName",
                  CASE a.attnotnull
                    WHEN true THEN 0
                    WHEN false then 1
                  END AS "nullable",
                  CASE
                    WHEN pg_get_serial_sequence(n.nspname||'.'||c.relname, a.attname) IS NULL
                    THEN false
                    ELSE true
                  END AS "isAutoIncrement"
                  FROM pg_class c
                  JOIN pg_namespace n ON n.oid = c.relnamespace
                  JOIN pg_attribute a ON attrelid = c.oid
                  WHERE c.oid = ANY($1::oid[])
                  ORDER BY a.attnum ASC
```

### PR DESCRIPTION
**Pull request by merlinorg**
Fixes #18.

### CODE REVIEW

**Review by dylanlt — APPROVED** [review]

**Comment by intmainvoid** [comment]
Would be super to get this merged and another package created. Let me know how I can help. I can confirm that this fix solves the problem for me.

**Comment by marcgreenstock** [comment]
Hi @merlinorg and @intmainvoid and @dylanlt,

First let me apologize, I've been unable to maintain this project due to other commitments and the lack of need for this in my current projects.

I would like to invite you all to become maintainers or even owners of this repo and npm package. If this is something you're interested in please let me know and I'll get it done.

Thanks for your understanding.

**Comment by intmainvoid** [comment]
> Hi @merlinorg and @intmainvoid and @dylanlt,
> 
> First let me apologize, I've been unable to maintain this project due to other commitments and the lack of need for this in my current projects.
> 
> I would like to invite you all to become maintainers or even owners of this repo and npm package. If this is something you're interested in please let me know and I'll get it done.
> 
> Thanks for your understanding.

Hey @marcgreenstock - that would be great. There's a few things we need to do to bring this library up to speed with Node 14+.

**Comment by merlinorg** [comment]
@marcgreenstock  I'd be happy to chip in, there are a couple of fixes for differences vs the AWS API that I should add.

**Review by intmainvoid — APPROVED** [review]

**Pull request merged**
